# Generated by Django 2.2.4 on 2019-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nome_autor', models.CharField(max_length=50)),
                ('assunto', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
