# Generated by Django 2.2.4 on 2019-08-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('textoTitulo', models.CharField(max_length=10)),
                ('preco', models.FloatField()),
                ('textoAnuncio', models.CharField(max_length=50)),
                ('nomeContato', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
                ('secao', models.CharField(max_length=50)),
                ('tipoAnucio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('qtdQuartos', models.IntegerField()),
                ('proprietario', models.CharField(max_length=10)),
                ('valorCondominio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricaoProduto', models.CharField(max_length=50)),
                ('unidadeCompra', models.CharField(max_length=10)),
                ('qtdPrevistoMes', models.FloatField()),
                ('preco', models.FloatField()),
                ('precoMaximo', models.FloatField()),
            ],
        ),
    ]
