# Generated by Django 2.2.4 on 2019-08-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_anuncio_apartamento_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
