# Generated by Django 2.2.4 on 2019-08-28 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apartamento_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartamento',
            name='valor',
        ),
    ]
